# See: https://github.com/github/super-linter
---
name: Linter
on:
  push:
    branches: [master]
    paths:
      - '**.dart'
      - '**.md'
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches: [master]
    paths:
      - '**.dart'
      - '**.md'
      - '**.yaml'
      - '**.yml'
jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Lint Markdown and YAML files
        uses: docker://github/super-linter:v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MD: true
          VALIDATE_YAML: true
      - name: Lint Dart source code
        uses: docker://github/super-linter:v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_DART: true
          DISABLE_ERRORS: true
